### PR TITLE
Fix for iOS not finding the image when using URL

### PR DESCRIPTION
**Pull request by stromgren**
Fixed issue where iOS would not find the image when using ImageResizer.IMAGE_DATA_TYPE_URL.
I have tested this in the iOS simulator and on an iPhone, both running iOS 8.2.

### CODE REVIEW

**Comment by RaananW** [comment]
Thanks a lot!

**Comment by stromgren** [comment]
Do you update the PhoneGap plugin so it can be used in PhoneGap build or is that one automatically?

**Comment by RaananW** [comment]
I assume phonegap build will use this repo and update it automatically, I will look into it.

**Comment by stromgren** [comment]
I've tested it and they do.

**Pull request merged**
